### ISSUE TITLE
Void Manager window will not close when I press F5.

### ISSUE THREAD

**Issue by ShadowDragon8685** [Void-Crew-Modding-Team/VoidManager#22]
As title says, the Void Manager Window will not close when I press F5, and I cannot find any button in Void Manager to close Void Manager.

**Comment by Nagord** [comment]
Thanks for reporting this issue. Is there anything noticeable in the console or Player.log file? To find it, paste the following into windows file explorer. `%localappdata%low\Hutlihut Games ApS\Void Crew`

Additionally, it may be faster to contact us on our [discord server](https://discord.gg/g2u5wpbMGu).

**Comment by Nagord** [comment]
Seems the issue was resolved and not reproduced via discord contact. Closing the issue.
